# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Bionic Ubuntu Linux"
      os: linux
      dist: bionic
      sudo: required
      env: TARGETOS=bionic-linux

# install, install QT5.12.3 from ppa
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-bionic
  - sudo apt update
  - sudo apt install build-essential g++ make ffmpeg sox mplayer libnotify-dev
  - sudo apt install qt-latest
  - echo "/opt/qt512/bin" | sudo tee /etc/xdg/qtchooser/default.conf
  - echo "/opt/qt512/lib" | sudo tee -a /etc/xdg/qtchooser/default.conf
  - qtchooser -print-env
  - qmake -v

# build & test scripts
script:
  - make clean
  - qmake mystiq.pro
  - make

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# no deploy section for now.
